# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wakeful_action.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'wakeful_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14wakeful_action.proto\x12\x0ewakeful_action\"\r\n\x0bWakeRequest\"!\n\x0eWakeSuccessful\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32Y\n\x0eWakefulService\x12G\n\x06WakeUp\x12\x1b.wakeful_action.WakeRequest\x1a\x1e.wakeful_action.WakeSuccessful\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wakeful_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAKEREQUEST']._serialized_start=40
  _globals['_WAKEREQUEST']._serialized_end=53
  _globals['_WAKESUCCESSFUL']._serialized_start=55
  _globals['_WAKESUCCESSFUL']._serialized_end=88
  _globals['_WAKEFULSERVICE']._serialized_start=90
  _globals['_WAKEFULSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
