# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import wakeful_action_pb2 as wakeful__action__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in wakeful_action_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WakefulServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WakeUp = channel.unary_unary(
                '/wakeful_action.WakefulService/WakeUp',
                request_serializer=wakeful__action__pb2.WakeRequest.SerializeToString,
                response_deserializer=wakeful__action__pb2.WakeSuccessful.FromString,
                _registered_method=True)


class WakefulServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WakeUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WakefulServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WakeUp': grpc.unary_unary_rpc_method_handler(
                    servicer.WakeUp,
                    request_deserializer=wakeful__action__pb2.WakeRequest.FromString,
                    response_serializer=wakeful__action__pb2.WakeSuccessful.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wakeful_action.WakefulService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wakeful_action.WakefulService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WakefulService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WakeUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wakeful_action.WakefulService/WakeUp',
            wakeful__action__pb2.WakeRequest.SerializeToString,
            wakeful__action__pb2.WakeSuccessful.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
